/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PieDemo {
    'config': string;
    'editor': boolean;
    'pie': string;
    'playerControls': boolean;
    'preview': boolean;
  }
  interface PieDemoAttributes extends StencilHTMLAttributes {
    'config'?: string;
    'editor'?: boolean;
    'pie'?: string;
    'playerControls'?: boolean;
    'preview'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PieDemo': Components.PieDemo;
  }

  interface StencilIntrinsicElements {
    'pie-demo': Components.PieDemoAttributes;
  }


  interface HTMLPieDemoElement extends Components.PieDemo, HTMLStencilElement {}
  var HTMLPieDemoElement: {
    prototype: HTMLPieDemoElement;
    new (): HTMLPieDemoElement;
  };

  interface HTMLElementTagNameMap {
    'pie-demo': HTMLPieDemoElement
  }

  interface ElementTagNameMap {
    'pie-demo': HTMLPieDemoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
